package my_source;
// Generated 27 May, 2016 7:38:28 PM by Hibernate Tools 4.3.1



/**
 * Store generated by hbm2java
 */
public class Store  implements java.io.Serializable {


     private int sno;
     private String item;
     private Integer rate;
     private Integer qty;
     private String offer;
     private Integer price;

    public Store() {
    }

	
    public Store(int sno) {
        this.sno = sno;
    }
    public Store(int sno, String item, Integer rate, Integer qty, String offer, Integer price) {
       this.sno = sno;
       this.item = item;
       this.rate = rate;
       this.qty = qty;
       this.offer = offer;
       this.price = price;
    }
   
    public int getSno() {
        return this.sno;
    }
    
    public void setSno(int sno) {
        this.sno = sno;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public Integer getRate() {
        return this.rate;
    }
    
    public void setRate(Integer rate) {
        this.rate = rate;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public String getOffer() {
        return this.offer;
    }
    
    public void setOffer(String offer) {
        this.offer = offer;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }




}


